"use client";
import {useEffect,useState} from "react";
type Game={id:string;title:string;category:string;description:string;featured:boolean};
export default function Home(){const [games,setGames]=useState<Game[]>([]);const [q,setQ]=useState("");const [me,setMe]=useState<any>(null);const [modal,setModal]=useState(false);const [request,setRequest]=useState("");const [msg,setMsg]=useState("");
useEffect(()=>{fetch("/api/games").then(r=>r.json()).then(x=>setGames(x.games||[]));fetch("/api/me").then(r=>r.json()).then(setMe)},[]);
const filtered=games.filter(g=>(g.title+" "+g.description+" "+g.category).toLowerCase().includes(q.toLowerCase()));
async function auth(){if(me){await fetch("/api/auth",{method:"DELETE"});location.reload()}else setModal(true)}
async function submit(){const r=await fetch("/api/requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:request})});const x=await r.json();setMsg(x.error||"Request submitted.");setRequest("")}
return <main><header><div className="brand"><span className="mark">GG</span><div><b>GG LOUNGE</b><small>2.0</small></div></div><nav><a href="#games">Games</a><a href="#requests">Requests</a><a href="#achievements">Achievements</a>{me?.isAdmin&&<a href="/admin">Admin</a>}<button onClick={auth}>{me?"Sign out":"Sign in"}</button></nav></header><section className="hero"><div><p className="eyebrow">THE NEXT VERSION</p><h1>GG Lounge <em>2.0</em></h1><p>A real gaming platform foundation. Your games come later — the infrastructure is ready now.</p><div className="actions"><a className="primary" href="#games">Browse games</a><a className="secondary" href="#requests">Request a game</a></div></div><div className="heroCard"><span>PLATFORM STATUS</span><strong>READY</strong><p>Accounts · Saves · Achievements · Requests · Admin</p></div></section><section id="games" className="section"><div className="sectionHead"><div><p className="eyebrow">LIBRARY</p><h2>Games</h2></div><input placeholder="Search games..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="grid">{filtered.map(g=><article className="game" key={g.id}><div className="thumb"><span>GAME</span></div><div className="gameBody"><div className="pill">{g.category}</div><h3>{g.title}</h3><p>{g.description}</p><button onClick={()=>location.href="/game/"+g.id}>Open</button></div></article>)}</div></section><section id="achievements" className="section split"><div><p className="eyebrow">PROFILE SYSTEM</p><h2>Achievements & cloud saves</h2><p>Sign in to keep progress, favourites, recently played games and achievement state attached to your account.</p></div><div className="featureList"><div>01 <b>Persistent saves</b><span>Game state belongs to your account.</span></div><div>02 <b>Real achievements</b><span>Unlocks are stored server-side.</span></div><div>03 <b>Moderation</b><span>Requests and blocks are admin-controlled.</span></div></div></section><section id="requests" className="section request"><p className="eyebrow">COMMUNITY</p><h2>Request a game</h2><div className="requestRow"><input value={request} onChange={e=>setRequest(e.target.value)} placeholder="Game title"/><button className="primary" onClick={submit}>Submit request</button></div>{msg&&<p className="notice">{msg}</p>}</section><footer>GG Lounge 2.0 · Built as a platform first.</footer>{modal&&<div className="overlay"><div className="modal"><button className="x" onClick={()=>setModal(false)}>×</button><h2>Sign in</h2><Auth onDone={()=>location.reload()}/></div></div>}</main>}
function Auth({onDone}:{onDone:()=>void}){const [login,setLogin]=useState(true);const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");async function go(){const r=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:login?"login":"signup",username,password})});const x=await r.json();if(!r.ok)setError(x.error||"Failed");else onDone()}return <div className="auth"><div className="tabs"><button onClick={()=>setLogin(true)} className={login?"active":""}>Sign in</button><button onClick={()=>setLogin(false)} className={!login?"active":""}>Create account</button></div><input placeholder="Username" value={username} onChange={e=>setUsername(e.target.value)}/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p className="error">{error}</p>}<button className="primary full" onClick={go}>{login?"Sign in":"Create account"}</button></div>}