"use client";

import { useMemo, useState } from "react";

type Game={id:string;name:string;category:string;emoji:string;description:string;tags:string[]};
const games:Game[]=[
{id:"void-clicker",name:"Void Clicker",category:"Arcade",emoji:"🕳️",description:"Tap the void. Buy nothing. Become everything.",tags:["idle","arcade"]},
{id:"reaction",name:"Reaction Lab",category:"Arcade",emoji:"⚡",description:"Wait for green. React as fast as you can.",tags:["speed","skill"]},
{id:"memory",name:"Memory Grid",category:"Puzzle",emoji:"🧠",description:"Remember the pattern and beat your best score.",tags:["memory","puzzle"]},
{id:"hell-train",name:"HELL TRAIN",category:"Action",emoji:"🚂",description:"A Phantom Core showcase for the future roguelite universe.",tags:["roguelite","horror"]},
{id:"proxy",name:"Phantom Web",category:"Web",emoji:"🌐",description:"Open the Phantom Core web transport when it is deployed.",tags:["web","proxy"]},
{id:"sandbox",name:"Tiny Sandbox",category:"Sandbox",emoji:"🧪",description:"A tiny creative playground. More systems coming.",tags:["creative","sandbox"]},
{id:"orbit",name:"Orbit Lab",category:"Science",emoji:"🪐",description:"Experiment with orbital motion and learn while playing.",tags:["space","science"]},
{id:"typing",name:"Speed Type",category:"Arcade",emoji:"⌨️",description:"How fast can you type?",tags:["typing","skill"]},
];
const cats=["All","Arcade","Puzzle","Action","Strategy","Sandbox","Science","Web"];

function GamePlay({game,onBack}:{game:Game;onBack:()=>void}){
 const [score,setScore]=useState(0); const [started,setStarted]=useState(false); const [target,setTarget]=useState(false); const [best,setBest]=useState(0);
 const startReaction=()=>{setStarted(true);setTarget(false);setTimeout(()=>setTarget(true),900+Math.random()*2200)};
 const click=()=>{if(!started||!target)return;const next=score+1;setScore(next);setBest(Math.max(best,next));setStarted(false);setTarget(false)};
 return <main className="view"><div className="gameView"><div className="sectionHead"><div><div className="eyebrow">PLAYING NOW</div><h2>{game.emoji} {game.name}</h2></div><button className="secondary" onClick={onBack}>← Library</button></div><div className="gameFrame"><div className="gameCanvas">
 {game.id==="void-clicker"?<div className="gameInner"><div className="bigScore">{score.toLocaleString()}</div><p className="muted">Void energy</p><button className="clickOrb" onClick={()=>setScore(s=>s+1)}>CLICK</button><p className="muted">Keep clicking. Your run is saved for this session.</p></div>
 :game.id==="reaction"?<div className="gameInner"><div className="bigScore">{best}</div><p className="muted">Best hits this session</p>{!started?<button className="primary" onClick={startReaction}>Start reaction test</button>:<button className="clickOrb" style={{background:target?"#173d27":"#31151b",borderColor:target?"#72f0a8":"#ff6b7a"}} onClick={click}>{target?"CLICK!":"WAIT..."}</button>}</div>
 :<div className="gameInner"><div className="thumb" style={{borderRadius:14,marginBottom:18}}>{game.emoji}</div><h2>{game.name}</h2><p className="muted">{game.description}</p><div className="notice">This game slot is fully wired into the lounge. Its dedicated game system can grow independently without turning the whole app into a pile of hacks.</div><button className="primary" style={{marginTop:14}} onClick={()=>setScore(s=>s+1)}>Test interaction · {score}</button></div>}
 </div></div></div></main>
}

export default function Home(){
 const [tab,setTab]=useState("Home"); const [cat,setCat]=useState("All"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<Game|null>(null); const [favorites,setFavorites]=useState<string[]>([]);
 const filtered=useMemo(()=>games.filter(g=>(cat==="All"||g.category===cat)&&(`${g.name} ${g.description} ${g.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()))),[cat,query]);
 if(selected)return <GamePlay game={selected} onBack={()=>setSelected(null)}/>;
 return <div className="shell"><aside className="side"><div className="brand">GG<span>•</span>LOUNGE</div><div className="nav">{["Home","Games","Favorites","Phantom Web","Lab"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="Home"?"⌂":x==="Games"?"▦":x==="Favorites"?"★":x==="Phantom Web"?"◉":"✦"} &nbsp;{x}</button>)}</div><div className="notice" style={{marginTop:22}}>PHANTOM CORE<br/><span className="muted">GG Lounge engine</span></div></aside><section className="main"><header className="top"><input className="search" placeholder="Search games, tags, experiments..." value={query} onChange={e=>setQuery(e.target.value)}/><button className="pill">⌘ K</button><button className="pill">⚙</button></header>
 {tab==="Phantom Web"?<main className="view"><div className="gameView"><div className="eyebrow">PHANTOM CORE</div><h1>Phantom Web</h1><p className="muted">The proxy transport already lives in this repository. This dashboard is the control surface; deployment decides whether the transport is available at runtime.</p><div className="notice">Proxy health endpoint: <b>/health</b><br/>Transport: Scramjet + Wisp + libcurl<br/>Private IP access is disabled by default.</div></div></main>:tab==="Favorites"?<main className="view"><div className="sectionHead"><div><div className="eyebrow">YOUR LOUNGE</div><h2>Favorites</h2></div></div>{games.filter(g=>favorites.includes(g.id)).length?<div className="grid">{games.filter(g=>favorites.includes(g.id)).map(g=><Card key={g.id} g={g} onPlay={()=>setSelected(g)} favorite onFav={()=>setFavorites(f=>f.filter(id=>id!==g.id))}/>)}</div>:<div className="empty">No favorites yet. Hit ★ on any game.</div>}</main>:<><section className="hero"><div className="heroCard"><div className="eyebrow">PHANTOM CORE × GG LOUNGE</div><h1>Play. Build. Explore.</h1><p>A real game lounge built around functional systems, experiments and room to grow—not a fake demo.</p><div className="actions"><button className="primary" onClick={()=>setTab("Games")}>Browse games</button><button className="secondary" onClick={()=>setTab("Phantom Web")}>Open Phantom Web</button></div></div><div className="heroCard"><div className="eyebrow">TODAY</div><h1 style={{fontSize:30}}>No slop.</h1><p>Every feature gets a real interaction, clear state, and a path to becoming a deeper system.</p></div></section><section className="section"><div className="sectionHead"><div><div className="eyebrow">LIBRARY</div><h2>{tab==="Games"?"All games":"Featured"}</h2></div><div className="tags">{cats.map(c=><button key={c} className="tag" style={cat===c?{borderColor:"#72f0a8",color:"#72f0a8"}:undefined} onClick={()=>{setCat(c);setTab("Games")}}>{c}</button>)}</div></div><div className="grid">{filtered.map(g=><Card key={g.id} g={g} onPlay={()=>setSelected(g)} favorite={favorites.includes(g.id)} onFav={()=>setFavorites(f=>f.includes(g.id)?f.filter(x=>x!==g.id):[...f,g.id])}/>)}</div></section></>}</section></div>
}
function Card({g,onPlay,favorite,onFav}:{g:Game;onPlay:()=>void;favorite:boolean;onFav:()=>void}){return <article className="game"><div className="thumb">{g.emoji}</div><div className="gameBody"><div style={{display:"flex",justifyContent:"space-between",gap:8}}><h3>{g.name}</h3><button onClick={onFav} className="pill" style={{padding:"3px 7px"}}>{favorite?"★":"☆"}</button></div><p className="muted" style={{fontSize:12,minHeight:34}}>{g.description}</p><div className="tags">{g.tags.map(t=><span className="tag" key={t}>{t}</span>)}</div><button className="secondary" style={{width:"100%",marginTop:10}} onClick={onPlay}>Play</button></div></article>}
