"use client";

import { useEffect, useMemo, useState } from "react";

type Game = { id:string; name:string; category:string; emoji:string; description:string; tags:string[]; accent:string };
const games:Game[]=[
{id:"void",name:"Void Clicker",category:"Arcade",emoji:"◉",description:"Turn clicks into a growing energy reactor.",tags:["idle","arcade"],accent:"violet"},
{id:"reaction",name:"Reaction Lab",category:"Arcade",emoji:"⚡",description:"Wait for the signal, then react. Beat your best time.",tags:["speed","skill"],accent:"green"},
{id:"memory",name:"Memory Grid",category:"Puzzle",emoji:"▦",description:"Watch the sequence and reproduce it. Endless difficulty.",tags:["memory","puzzle"],accent:"blue"},
{id:"target",name:"Target Rush",category:"Action",emoji:"⊙",description:"Hit moving targets before the timer runs out.",tags:["aim","arcade"],accent:"red"},
{id:"typing",name:"Speed Type",category:"Arcade",emoji:"⌨",description:"Type the phrase as quickly and accurately as possible.",tags:["typing","skill"],accent:"yellow"},
{id:"orbit",name:"Orbit Lab",category:"Science",emoji:"◎",description:"Tune velocity and watch a simple orbital simulation.",tags:["space","science"],accent:"cyan"},
{id:"hell-train",name:"HELL TRAIN",category:"Action",emoji:"🚂",description:"The future home of the full supernatural roguelite.",tags:["roguelite","horror"],accent:"orange"},
{id:"sandbox",name:"Tiny Sandbox",category:"Sandbox",emoji:"✦",description:"Place particles and build tiny experiments.",tags:["creative","sandbox"],accent:"pink"},
{id:"number",name:"Number Forge",category:"Puzzle",emoji:"#",description:"Reach the target using arithmetic choices.",tags:["math","logic"],accent:"indigo"},
{id:"phantom",name:"Phantom Web",category:"Web",emoji:"⌁",description:"Launch the Phantom Core transport when its service is available.",tags:["proxy","web"],accent:"white"},
];
const cats=["All","Arcade","Puzzle","Action","Strategy","Sandbox","Science","Web"];

function MiniGame({game,onBack}:{game:Game;onBack:()=>void}){
 const [score,setScore]=useState(0); const [best,setBest]=useState(0); const [running,setRunning]=useState(false); const [target,setTarget]=useState(false); const [startedAt,setStartedAt]=useState(0); const [pattern,setPattern]=useState<number[]>([]); const [input,setInput]=useState<number[]>([]); const [level,setLevel]=useState(1); const [time,setTime]=useState(15); const [orb,setOrb]=useState({x:50,y:50}); const [typed,setTyped]=useState("");
 const phrases=["build something real","no ai slop","explore the universe","phantom core","play build explore"];
 useEffect(()=>{const key=`gg-best-${game.id}`;const n=Number(localStorage.getItem(key)||0);setBest(n)},[game.id]);
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setTime(t=>{if(t<=1){setRunning(false);return 0}return t-1}),1000);return()=>clearInterval(id)},[running]);
 const save=(n:number)=>{setBest(b=>Math.max(b,n));localStorage.setItem(`gg-best-${game.id}`,String(Math.max(best,n)))};
 const startReaction=()=>{setRunning(true);setTarget(false);setStartedAt(0);setTimeout(()=>{setTarget(true);setStartedAt(performance.now())},700+Math.random()*2300)};
 const reactionClick=()=>{if(!target)return;const ms=Math.round(performance.now()-startedAt);setScore(ms);save(999999-ms);setRunning(false);setTarget(false)};
 const newMemory=()=>{const next=[...pattern,Math.floor(Math.random()*4)];setPattern(next);setInput([]);setLevel(next.length);setRunning(true)};
 const memoryClick=(n:number)=>{if(!running)return;const next=[...input,n];setInput(next);if(next[next.length-1]!==pattern[next.length-1]){setRunning(false);save(level-1);return}if(next.length===pattern.length){setRunning(false);save(level);setTimeout(()=>{const p=[...pattern,Math.floor(Math.random()*4)];setPattern(p);setInput([]);setLevel(p.length);setRunning(true)},500)}};
 const startTarget=()=>{setScore(0);setTime(15);setRunning(true);setOrb({x:10+Math.random()*80,y:10+Math.random()*70})};
 const targetClick=()=>{if(!running)return;const n=score+1;setScore(n);setOrb({x:10+Math.random()*80,y:10+Math.random()*70});save(n)};
 const startTyping=()=>{setTyped("");setScore(0);setTime(20);setRunning(true)};
 const phrase=phrases[score%phrases.length];
 return <main className="view"><div className="gameView"><div className="sectionHead"><div><div className="eyebrow">PLAYING NOW · {game.category}</div><h1>{game.emoji} {game.name}</h1></div><button className="secondary" onClick={onBack}>← Library</button></div><div className="gameFrame"><div className={`gameCanvas accent-${game.accent}`}>
 {game.id==="void"&&<div className="gameInner"><div className="bigScore">{score.toLocaleString()}</div><p className="muted">VOID ENERGY · BEST {best.toLocaleString()}</p><button className="clickOrb" onClick={()=>{const n=score+1;setScore(n);save(n)}}>CLICK</button><p className="muted">Every click is real state. Progress persists on this device.</p></div>}
 {game.id==="reaction"&&<div className="gameInner"><div className="bigScore">{running&&target?"NOW!":"READY?"}</div><p className="muted">Best score: {best>0?`${best} pts`:"—"}</p>{!running?<button className="primary" onClick={startReaction}>Start</button>:<button className={`reactionButton ${target?"go":"wait"}`} onClick={reactionClick}>{target?"CLICK!":"WAIT..."}</button>}{score>0&&<p className="result">{score} ms</p>}</div>}
 {game.id==="memory"&&<div className="gameInner"><h2>Level {level}</h2><div className="memoryGrid">{[0,1,2,3].map(n=><button key={n} className={`memoryCell ${input.includes(n)?"chosen":""}`} onClick={()=>memoryClick(n)}>{n+1}</button>)}</div>{!running&&<button className="primary" onClick={()=>{const p=[Math.floor(Math.random()*4)];setPattern(p);setInput([]);setLevel(1);setRunning(true)}}>{level>1?"Try again":"Start"}</button>}<p className="muted">Best level: {best}</p></div>}
 {game.id==="target"&&<div className="gameInner targetGame"><div className="hud">TIME {time}s · HITS {score} · BEST {best}</div>{running?<button className="target" style={{left:`${orb.x}%`,top:`${orb.y}%`}} onClick={targetClick}>+</button>:<button className="primary" onClick={startTarget}>Start rush</button>}</div>}
 {game.id==="typing"&&<div className="gameInner"><div className="bigScore">{time}s</div><p className="muted">Type exactly:</p><h2 className="typePhrase">{phrase}</h2><input autoFocus className="typeInput" disabled={!running} value={typed} onChange={e=>{const v=e.target.value;setTyped(v);if(v===phrase){setScore(s=>s+1);setTyped("")}}}/>{!running&&<button className="primary" onClick={startTyping}>Start typing</button>}<p className="muted">Completed: {score} · Best: {best}</p></div>}
 {game.id==="orbit"&&<Orbit/>}
 {game.id==="sandbox"&&<Sandbox/>}
 {game.id==="number"&&<NumberForge onScore={save}/>} 
 {game.id==="hell-train"&&<div className="gameInner"><div className="train">🚂</div><h2>HELL TRAIN</h2><p className="muted">The lounge shell is ready for the full game systems to plug in here.</p><div className="notice">Next deep-game module: procedural runs, combat, upgrades, train systems, bosses, VFX and persistent progression.</div></div>}
 {game.id==="phantom"&&<div className="gameInner"><h2>Phantom Web</h2><p className="muted">This UI connects to the real proxy service; it does not pretend a proxy exists when it is not deployed.</p><a className="primary linkButton" href="/proxy">Open proxy control</a></div>}
 </div></div></div></main>
}
function Orbit(){const [v,setV]=useState(7);return <div className="gameInner"><div className="orbitScene"><div className="planet">●</div><div className="sat" style={{transform:`rotate(${Date.now()/1000%360}deg) translateX(${v*9}px)`}}>●</div></div><h2>Orbital velocity: {v}</h2><input type="range" min="1" max="12" value={v} onChange={e=>setV(Number(e.target.value))}/><p className="muted">A toy model: change velocity and see how the orbit tendency changes.</p></div>}
function Sandbox(){const [dots,setDots]=useState<{x:number;y:number}[]>([]);return <div className="gameInner"><div className="sandbox" onClick={e=>{const r=e.currentTarget.getBoundingClientRect();setDots(d=>[...d,{x:e.clientX-r.left,y:e.clientY-r.top}])}}>{dots.map((d,i)=><i key={i} style={{left:d.x,top:d.y}}/>)}<span>CLICK TO CREATE</span></div><button className="secondary" onClick={()=>setDots([])}>Clear</button><p className="muted">Simple creative space—designed to grow into a real lab.</p></div>}
function NumberForge({onScore}:{onScore:(n:number)=>void}){const [target]=useState(()=>20+Math.floor(Math.random()*30));const [value,setValue]=useState(0);const [done,setDone]=useState(false);return <div className="gameInner"><h2>Reach {target}</h2><div className="bigScore">{value}</div><div className="numberBtns">{[1,2,3,5,7].map(n=><button key={n} className="secondary" onClick={()=>setValue(v=>Math.min(target,v+n))}>+{n}</button>)}{[2,3].map(n=><button key={`x${n}`} className="secondary" onClick={()=>setValue(v=>Math.min(target,v*n))}>×{n}</button>)}</div>{value===target&&!done&&<button className="primary" onClick={()=>{setDone(true);onScore(1)}}>Solved!</button>}{done&&<p className="result">Solved. +1 best.</p>}</div>}

export default function Home(){
 const [tab,setTab]=useState("Home");const [cat,setCat]=useState("All");const [query,setQuery]=useState("");const [selected,setSelected]=useState<Game|null>(null);const [favorites,setFavorites]=useState<string[]>([]);const [cursor,setCursor]=useState("default");const [dark,setDark]=useState(true);
 useEffect(()=>{try{setFavorites(JSON.parse(localStorage.getItem("gg-favorites")||"[]"));setCursor(localStorage.getItem("gg-cursor")||"default");setDark(localStorage.getItem("gg-dark")!=="false")}catch{}} ,[]);
 useEffect(()=>{localStorage.setItem("gg-favorites",JSON.stringify(favorites));localStorage.setItem("gg-cursor",cursor);localStorage.setItem("gg-dark",String(dark));document.documentElement.dataset.cursor=cursor;document.documentElement.dataset.theme=dark?"dark":"light"},[favorites,cursor,dark]);
 const filtered=useMemo(()=>games.filter(g=>(cat==="All"||g.category===cat)&&(`${g.name} ${g.description} ${g.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()))),[cat,query]);
 if(selected)return <MiniGame game={selected} onBack={()=>setSelected(null)}/>;
 const list=tab==="Favorites"?games.filter(g=>favorites.includes(g.id)):filtered;
 return <div className="shell"><aside className="side"><div className="brand">GG<span>•</span>LOUNGE</div><div className="nav">{["Home","Games","Favorites","Phantom Web","Lab"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="Home"?"⌂":x==="Games"?"▦":x==="Favorites"?"★":x==="Phantom Web"?"◉":"✦"} <span>{x}</span></button>)}</div><div className="sideBottom"><div className="notice">PHANTOM CORE<br/><span className="muted">GG Lounge engine</span></div><button className="secondary full" onClick={()=>setDark(d=>!d)}>{dark?"☀ Light":"☾ Dark"}</button><select className="select" value={cursor} onChange={e=>setCursor(e.target.value)}><option value="default">Default cursor</option><option value="crosshair">Precision cursor</option><option value="cell">Retro cursor</option></select></div></aside><section className="main"><header className="top"><input className="search" placeholder="Search games, tags, experiments..." value={query} onChange={e=>setQuery(e.target.value)}/><span className="status">● SYSTEM ONLINE</span></header>{tab==="Phantom Web"?<main className="view"><div className="gameView"><div className="eyebrow">PHANTOM CORE</div><h1>Phantom Web</h1><p className="muted">Real transport surface for the proxy already living in this repository.</p><div className="notice">Scramjet + Wisp + libcurl transport<br/>Private-IP access protection remains enabled.<br/>Use the proxy control page only when the service is actually deployed.</div><a className="primary linkButton" href="/proxy">Open proxy</a></div></main>:tab==="Lab"?<Lab/>:<><section className="hero"><div className="heroCard"><div className="eyebrow">PHANTOM CORE × GG LOUNGE</div><h1>Play. Build. Explore.</h1><p>A real lounge for games, experiments and the things you want to make—not a decorative fake.</p><div className="actions"><button className="primary" onClick={()=>setTab("Games")}>Browse games</button><button className="secondary" onClick={()=>setTab("Lab")}>Open Lab</button></div></div><div className="heroCard compact"><div className="eyebrow">DESIGN RULE</div><h2>No slop.</h2><p>Every visible control has a real interaction or a clear boundary around what is not built yet.</p></div></section><section className="section"><div className="sectionHead"><div><div className="eyebrow">{tab==="Favorites"?"YOUR PICKS":"LIBRARY"}</div><h2>{tab==="Games"?"All games":tab==="Favorites"?"Favorites":"Featured"}</h2></div><div className="tags">{cats.map(c=><button key={c} className={`tag ${cat===c?"selected":""}`} onClick={()=>{setCat(c);setTab("Games")}}>{c}</button>)}</div></div>{list.length?<div className="grid">{list.map(g=><Card key={g.id} g={g} favorite={favorites.includes(g.id)} onFav={()=>setFavorites(f=>f.includes(g.id)?f.filter(x=>x!==g.id):[...f,g.id])} onPlay={()=>setSelected(g)}/>)}</div>:<div className="empty">Nothing matches. Try another search.</div>}</section></>}</section></div>
}
function Lab(){return <main className="view"><div className="gameView"><div className="eyebrow">CREATIVE LAB</div><h1>Build, test, learn.</h1><p className="muted">The Lab is the place for experiments that can later become full GG Lounge systems.</p><div className="labGrid"><div className="notice"><b>Game Forge</b><br/>Prototype mechanics without polluting the main library.</div><div className="notice"><b>Science Lab</b><br/>Small simulations for space, maths and physics.</div><div className="notice"><b>Style Lab</b><br/>Cursors, backgrounds and interaction experiments.</div><div className="notice"><b>AI Lab</b><br/>A real integration point—not a fake chat box. Provider wiring comes after credentials/runtime are available.</div></div></div></main>}
function Card({g,onPlay,favorite,onFav}:{g:Game;onPlay:()=>void;favorite:boolean;onFav:()=>void}){return <article className="game"><div className={`thumb accent-${g.accent}`}>{g.emoji}</div><div className="gameBody"><div className="cardTitle"><h3>{g.name}</h3><button onClick={onFav} className="pill" aria-label="favorite">{favorite?"★":"☆"}</button></div><p className="muted desc">{g.description}</p><div className="tags">{g.tags.map(t=><span className="tag" key={t}>{t}</span>)}</div><button className="secondary full" onClick={onPlay}>Play</button></div></article>}
